### ISSUE TITLE
Validation does not woking because of the removal of fluent errors

### ISSUE THREAD

**Issue by octoper** [confetti-framework/framework#1]
Inside the `rule` directory the errors file uses fluent errors, but that is deprecated.

**Comment by reindert-vetter** [comment]
Oops, I did deprecated fluent errors recently. That's because fluent error doesn't really work well after all. Ultimately, it's better to just use https://github.com/confetti-framework/errors. I'll see if I can get it straight in confetti framework/framework today.

**Comment by reindert-vetter** [comment]
I've solved the problem. The validation tests are now successful again.

**Comment by octoper** [comment]
Nice!
